(load "test_helper")

(describe "Application" `(
  (it "initializes with attributes" (do ()
    (set attributes (NSMutableDictionary dictionary))
    (attributes setValue:"test.host" forKey:"host")
    (attributes setValue:"assets.test.host" forKey:"aliases")
    (attributes setValue:"/path/to/test" forKey:"path")
    (attributes setValue:"production" forKey:"environment")
    (attributes setValue:"/path/to/test.conf" forKey:"config_filename")
    (set application ((Application alloc) initWithAttributes:attributes))
    
    (~ application host should be:"test.host")
    (~ application aliases should be:"assets.test.host")
    (~ application path should be:"/path/to/test")
    (~ application environment should be:1)
    (~ application configFilename should be:"/path/to/test.conf")
  ))
  
  (it "initializes with attributes, even when the environment is not passed" (do ()
    (set attributes (NSMutableDictionary dictionary))
    (attributes setValue:"test.host" forKey:"host")
    (set application ((Application alloc) initWithAttributes:attributes))
    (~ application host should be:"test.host")
  ))
  
  (it "initializes with a directory" (do ()
    (set directory "/path/to/test")
    (set application ((Application alloc) initWithDirectory:directory))
    (~ application path should be:directory)
    (~ application host should be:"test.local")
  ))
  
  (it "updates its attributes" (do ()
    (set application ((Application alloc) init))
    (set attributes (NSMutableDictionary dictionary))
    (attributes setValue:"test.host" forKey:"host")
    (attributes setValue:"assets.test.host" forKey:"aliases")
    (attributes setValue:"/path/to/test" forKey:"path")
    (attributes setValue:"production" forKey:"environment")
    (attributes setValue:"/path/to/test.conf" forKey:"config_filename")
    
    (application updateAttributes:attributes)
    
    (~ application host should be:"test.host")
    (~ application aliases should be:"assets.test.host")
    (~ application path should be:"/path/to/test")
    (~ application environment should be:1)
    (~ application configFilename should be:"/path/to/test.conf")
  ))
))

(describe "An Application" `(
  (before (do ()
    (set @attributes (NSMutableDictionary dictionary))
    (@attributes setValue:"test.host" forKey:"host")
    (@attributes setValue:"assets.test.host" forKey:"aliases")
    (@attributes setValue:"/path/to/test" forKey:"path")
    (@attributes setValue:"production" forKey:"environment")
    (@attributes setValue:"/path/to/test.conf" forKey:"config_filename")
    (set @application ((Application alloc) initWithAttributes:@attributes))
  ))
  
  (it "converts its attributes to a dictionary" (do ()
    (set attributes (@application toDictionary))
    (~ (attributes objectForKey:"host") should be:"test.host")
    (~ (attributes objectForKey:"aliases") should be:"assets.test.host")
    (~ (attributes objectForKey:"path") should be:"/path/to/test")
    (~ (attributes objectForKey:"environment") should be:"production")
    (~ (attributes objectForKey:"config_filename") should be:"/path/to/test.conf")
  ))
  
  (it "converts to an argument array" (do ()
    (set arguments (@application toArgumentArray))
    (~ (arguments list) should equal:`("-path" "/path/to/test" "-environment" "production" "-host" "test.host" "-config_filename" "/path/to/test.conf" "-aliases" "assets.test.host"))
  ))
))

(describe "An Application, concering validation" `(
  (it "is invalid without host and path" (do ()
    (set application ((Application alloc) init))
    (application validate)
    (~ (application isValid) should be:0)
  ))
  
  (it "is invalid with just a host" (do ()
    (set attributes (NSMutableDictionary dictionary))
    (attributes setValue:"test.host" forKey:"host")
    (set application ((Application alloc) initWithAttributes:attributes))
    (application validate)
    (~ (application isValid) should be:0)
  ))
  
  (it "is valid with a host and a path" (do ()
    (set attributes (NSMutableDictionary dictionary))
    (attributes setValue:"/path/to/test" forKey:"path")
    (set application ((Application alloc) initWithAttributes:attributes))
    (application validate)
    (~ (application isValid) should be:1)
  ))
))

((Bacon sharedInstance) run)